import type { Metadata } from "next";
import localFont from "next/font/local";
import "/globals.css";
import { SupabaseProvider } from "@/components/SupabaseProvider";
import { Toaster } from "sonner";
import { NotificationProvider } from "@/components/NotificationContext";
import { getCurrentUser } from "@/lib/auth";
// import { checkDailyMedications } from "@/lib/actions/prescription.actions";
import { useEffect } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Pharma App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  // useEffect(() => {
  //   const checkMedications = async () => {
  //     const now = new Date();
  //     if (now.getHours() === 9) {
  //       await checkDailyMedications();
  //     }
  //   };

  //   const interval = setInterval(checkMedications, 1000 * 60 * 60 * 24);
  //   checkMedications();

  //   return () => clearInterval(interval);
  // }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-200 w-full`}
      >
        <SupabaseProvider>
          <NotificationProvider userId={user?.id || ""}>
            {children}
          </NotificationProvider>
        </SupabaseProvider>
        <Toaster />
      </body>
    </html>
  );
}
